/*
 * generated by Xtext 2.12.0
 */
package eu.quanticol.jsstl.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class JSSTLScriptStandaloneSetup extends JSSTLScriptStandaloneSetupGenerated {

	def static void doSetup() {
		new JSSTLScriptStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
